esphome:
  name: test

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
#api:
#  password: ""

mqtt:
  broker: 192.168.2.50
  birth_message:
    topic: myavailability/topic
    payload: online
  will_message:
    topic: myavailability/topic
    payload: offline

ota:
  password: ""

wifi:
  ssid: !secret WifiSsid 
  password: !secret WifiPassword 

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: !secret apWifiPassword

web_server:
  port: 80


# Example configuration entry
dallas:
  - pin: GPIO4

# Individual sensors
sensor:
  - platform: dallas
    address: 0xed3c2ae381316128 
    name: "Pool Temperature"
    accuracy_decimals: 3
  - platform: dallas
    address: 0xcb3cdfe38160b528
    name: "Local temperature"
    accuracy_decimals: 3
captive_portal:
    
